name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16 
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Upload histogram artifact
      uses: actions/upload-artifact@v2
      with:
        name: gaussian-histogram
        path: gaussian_histogram.png
