name: Run Examples
on: [push]
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10.16 
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16 
      
      - name: Install dependencies
        run: |
          make install
      
      - name: Run examples
        run: |
          make examples

      - name: Upload histogram artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
